### ISSUE TITLE
您好，请问支持hadoop的版本是什么？

### ISSUE THREAD

**Issue by 20100507** [jizhang/zabbix-templates#13]
Item preprocessing step #1 failed: cannot convert value "sh: /etc/zabbix/scripts/hadoop-collector.py: No such file or directory" of type "string" from boolean format: invalid value format

`None of the groups in list "hadoop2" is correct.`
我的hadoop不是高可用集群，请问可以这么解决，cluster_name是在高可用集群下的，自己设置的名称么？
谢谢了~~

**Comment by jizhang** [comment]
@20100507 hi 建议使用 CDH 社区版搭建 Hadoop 集群，里面提供了完整的监控报警设施。这套 Zabbix 脚本已经年久失修了，不建议使用。谢谢你的关注。
