### ISSUE TITLE
nginx documentation doesn't mention nginx-check.sh

### ISSUE THREAD

**Issue by c-nichols** [jizhang/zabbix-templates#5]
Hi there, thanks for sharing these.  When configuring the nginx template I noticed that your readme doesn't mention the nginx-check.sh file -- might be nice to add a step to the instructions :)

**Comment by robsonmantovani** [comment]
Hello there,

I create a PR to correct this. 
Nice template! It's very useful.

Thank you very much!

**Comment by robsonmantovani** [comment]
We can close this! 

Thank you very much!
